export const SET_SCROLL_TOP = "SET_SCROLL_TOP";

export const SET_PLAYLIST = "SET_PLAYLIST";

export const SET_CURRENT_INDEX = "SET_CURRENT_INDEX";

export const SET_FULL_SCREEN = "SET_FULL_SCREEN";

export const SET_PLAYING = "SET_PLAYING";

export const SET_USER = "SET_USER";

export const SET_FAVORITE_LIST = "SET_FAVORITE_LIST";

export const SET_PLAY_HISTORY = "SET_PLAY_HISTORY";
